defaults:
  - model: deepspeech
  - writer: wandb_inf
  - metrics: example
  - datasets: example_eval # we do not want to run inference on training data
  - dataloader: dataloader_ds
  - transforms: deepspeech_transforms
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "inference" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/deepspeech_base/model_best.pth" # path to the pretrained model
